# Create index.html

name: create index

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  create:
    name: Create
    runs-on: ubuntu-latest
    steps:
    - name: Install Pandoc
      run: sudo apt-get install -y pandoc
    - uses: actions/checkout@v2
    - name: Create index.md
      run: ./create.sh index.md
    - name: git commit
      run: |
          git config --global user.name 'indexbot_53845714'
          git config --global user.email 'indexbot_53845714@users.noreply.github.com'
          git add index.html
          git commit -m "new index.html"
          git push
