# Create index.html
name: create index

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  create:
    name: Create
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run pandoc
      uses: docker://pandoc/core:2.14.2    
      with:
        args: >-                               
          -s
          -t revealjs
          --slide-level=3
          --variable theme="league"
          --output=index.html
          index.md
    - name: Deploy on github pages              
        uses: JamesIves/github-pages-deploy-action@4.1.0
          with:
            branch: main
